name: Autograding Workflow

on:
  push:
    branches:
      - main # This triggers the workflow when a PR is opened or updated

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }} # Ensures tests run on the PR branch

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Updated from "14" to "18"

      - name: Install dependencies
        run: npm install # Assuming the project uses npm for package management

      - name: Run tests
        run: npm test # Or specify the command to run your test cases

      
